### ISSUE TITLE
Change the way we list TV Shows (and Movies)

### ISSUE THREAD

**Issue by danielfc** [kalnee/blendsubs#1]
We should improve the way the user chooses the TV show and Movies, especially TV Shows where we have seasons and episodes.

**Comment by danielfc** [comment]
Yep, it's working with the latest version: https://blendsubs.herokuapp.com/

It just needs some tweaks like:
- the `description` property from iMdb API contains HTML 
- what should we do if the item is a TV show? Choose the episode?

**Comment by joaomcar** [comment]
Yeah, maybe another step where the user can choose an episode from a list.

**Comment by danielfc** [comment]
I think we could follow the approach used by `legendas.tv` where they show the TV show and the season as one item in the list, like:

![legendas.tv](https://s32.postimg.org/6mxokbyfp/Screenshot_from_2016_06_19_14_24_07.png)

Then the user chooses the episode in another step, each episode will download a zip containing all possible subtitles for that episode in pt-br.

**Comment by joaomcar** [comment]
Done via #14.
